# Generated by Django 4.2.5 on 2023-11-11 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 11, 12, 41, 31, 485097, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
