# Generated by Django 4.2.5 on 2023-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="genres",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
